export const inventory = {
    prefix: 'inventory',

    paths: [
        { url: 'storeDepartments', pagination: false },
        { url: 'taxCategories', pagination: false },
        { url: 'measurementUnits', pagination: false },
        { url: 'productCategories', pagination: false },
        { url: 'productMeasurements', pagination: false },
        { url: 'products', pagination: false },
        { url: 'stores', pagination: false },
        { url: 'storeDepartments', pagination: false },
        { url: 'storeProducts', pagination: false },
        { url: 'requisitions', pagination: false },
        { url: 'suppliers', pagination: false },
        { url: 'paymentTerms', pagination: false },
        { url: 'invoices', pagination: false },
        { url: 'goodsReceivedNotes', pagination: false },
        { url: 'goodsReceived', pagination: false },
        { url: 'internalOrders', pagination: false },
        { url: 'order', pagination: false },
        { url: 'purchaseOrders', pagination: false },
        { url: 'supplierSummary', pagination: false },
        { url: 'supplierStatement', pagination: false },
        { url: 'approvalLevels', pagination: false },
        { url: 'stockTake', pagination: false },
        { url: 'stockTakeDetails', pagination: false },
        { url: 'activityLogs', pagination: false },
        { url: 'grns', pagination: false },
        { url: 'inventoryPosSales', pagination: false },
        { url: 'inventorySaleDetails', pagination: false },
        { url: 'pointsOfSale', pagination: false },
        { url: 'stockMovement', pagination: false },
        { url: 'dispatchesReport', pagination: false },
        { url: 'stockValue', pagination: false },
    ],
};
