export const fields = {
    visit_id: null,
    patient_id: null,
    admission_id: null,
    inductionOfLabor: '',
    labourDuration: '',
    vesNumber: '',
    deliveryMode: '',
    deliveryDuration: '',
    inductionMedication: '',
    iv: '',
    im:false,
    both:false,
    babyAliveApgarMin: '',
    babyAliveApgar5min: '',
    babyAliveApgar10min: '',
    resuscitation: '',
    resuscitationDuration: '',
    placenta: '',
    wl: '',
    membrane: '',
    cord: '',
    bloodLoss: '',
    perinealTear: '',
    perinealIntact:'',
    perineal_status:'',
    episiotomy: '',
    motherBpDiastolic: '',
    motherBpSystolic: '',
    motherPulse: '',
    motherTemp: '',
    motherResp: '',
    babyWeight: '',
    babyLength: '',
    babyHead: '',
    drugsGiven: '',
    deliveredBy: '',
    deliveryDateTime: '',
    selection: ''
};
