export const fields = {
    is_pharmacy: false,
    station_id: null,
    is_sfaff: null,
    customer: {
        staff_id: null,
        customer_identifier: null,
    },
    pharmacy: {
        use_insurance: null,
        patient: null,
        scheme: null,
        new_patient: null,
        selected_drugs: [
            {
                id: null,
                name: null,
                route: null,
                frequency: 1,
                dosage: 1,
                duration: null,
                measure: null,
                quantity: null,
                orderable_quantity: null,
                selling_price: null,
                amount: null,
                total: null,
                product_id: null,
                product_type: null,
            },
            {
                id: null,
                name: null,
                route: null,
                frequency: 1,
                dosage: 1,
                duration: null,
                measure: null,
                quantity: null,
                orderable_quantity: null,
                selling_price: null,
                amount: null,
                total: null,
                product_id: null,
                product_type: null,
            },
            {
                id: null,
                name: null,
                route: null,
                frequency: 1,
                dosage: 1,
                duration: null,
                measure: null,
                quantity: null,
                orderable_quantity: null,
                selling_price: null,
                amount: null,
                total: null,
                product_id: null,
                product_type: null,
            },
        ],
    },

    total_cost: 0,
    selectedItems: [
        {
            id: null,
            name: null,
            quantity: null,
            orderable_quantity: null,
            product_id: null,
            selling_price: null,
            amount: null,
            total: null,
        },
        {
            id: null,
            name: null,
            quantity: null,
            orderable_quantity: null,
            product_id: null,
            selling_price: null,
            amount: null,
            total: null,
        },
        {
            id: null,
            name: null,
            quantity: null,
            orderable_quantity: null,
            product_id: null,
            selling_price: null,
            amount: null,
            total: null,
        },
    ],
};
