export const fields = {
    patient_id: null,
    // contact: null,
    // mobile: null,
    // telephone: null,
    // location_name: null,
    // lat: null,
    // long: null,
    // email: null,
    // secondary_email: null,
    // address: null,
    comments: null,
    trackees: [],
    details: {
        profile: {
            first_name: null,
            middle_name: null,
            last_name: null,
            mobile: null,
            id_no: null,
            dob: null,
            age: null,
            age_in: null,
            sex: null,
            town: null,
            email: null,
            secondary_email: null,
            resident_county: null,
            nationality: null,
            resident_sub_county: null,
            resident_village: null,
        },
        contact_id: null,
        symptom_details: [],
        has_symptoms: false,
        is_health_care_worker: false,
        head_of_household: null,
        type_of_contact: null
    },

    contact_trace_update: {
        has_travelled: false,
        arrival_date: null,
        call_status: null,
        tracking_status: null,
        comments: null,
        contact_id: null,
    },
};
